"""empty message

Revision ID: dbfcb70cd222
Revises: 
Create Date: 2021-10-30 11:05:28.322471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfcb70cd222'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('sqlite_sequence')
    # op.add_column('Author', sa.Column('valide', sa.Boolean(), nullable=True))
    # op.add_column('ReferenceBibliographiqueLivre', sa.Column('valide', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('ReferenceBibliographiqueLivre', 'valide')
    # op.drop_column('Author', 'valide')
    # op.create_table('sqlite_sequence',
    # sa.Column('name', sa.NullType(), nullable=True),
    # sa.Column('seq', sa.NullType(), nullable=True)
    # )
    # ### end Alembic commands ###
    pass
