"""
Add ARK names to resources.
Add authors_form to book references.
Increase length of password hash and link for validation.


Revision ID: f5f226876a68
Revises: dbfcb70cd222
Create Date: 2024-03-28 10:57:40.838152

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'f5f226876a68'
down_revision = 'dbfcb70cd222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Author2023', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ark_name', sa.String(length=128), nullable=True))

    with op.batch_alter_table('Enregistrement2023', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ark_name', sa.String(length=128), nullable=True))

    with op.batch_alter_table('ReferenceBibliographiqueLivre2023', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authors_form', sa.String(length=1024), nullable=True, default=""))
        batch_op.add_column(sa.Column('ark_name', sa.String(length=128), nullable=True))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('mdp_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=4096),
               existing_nullable=False)
        batch_op.alter_column('link_to_validate',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.alter_column('link_to_validate',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
        batch_op.alter_column('mdp_hash',
               existing_type=sa.String(length=4096),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    with op.batch_alter_table('ReferenceBibliographiqueLivre2023', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ark_name')
        batch_op.drop_column('authors_form')

    with op.batch_alter_table('Enregistrement2023', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ark_name')

    with op.batch_alter_table('Author2023', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('ark_name')

    # ### end Alembic commands ###
